name: tellopy
channels:
  - https://conda.anaconda.org/menpo
  - conda-forge
dependencies:
  - python==3.5.2
  - numpy
  - opencv3
  - scikit-learn
  - scikit-image
  - av
  - pip:
    - https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.3.0-py3-none-any.whl
    - keras==2.0.9
    - tellopy
    - image
